name: flutter_math
description: Fast and high-quality TeX math equation rendering with pure Dart & Flutter.
version: 0.4.0
author: znjameswu <znjameswu@gmail.com>
homepage: https://github.com/znjameswu/flutter_math
repository: https://github.com/znjameswu/flutter_math

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.24.0-6.0.pre"
  # Flutter has a breaking change in ParentDataWidget in 1.17.0 https://flutter.dev/docs/release/breaking-changes/parent-data-widget-generic-type
  # FLutter has a breaking change in LayoutBuilder in 1.18.0

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  meta: ^1.7.0
  provider: ^6.0.1
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: KaTeX_Main
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Main-Regular.ttf
        - asset: lib/katex_fonts/fonts/KaTeX_Main-Italic.ttf
          style: italic
        - asset: lib/katex_fonts/fonts/KaTeX_Main-Bold.ttf
          weight: 700
        - asset: lib/katex_fonts/fonts/KaTeX_Main-BoldItalic.ttf
          weight: 700
          style: italic
    - family: KaTeX_Math
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Math-Italic.ttf
          style: italic
        - asset: lib/katex_fonts/fonts/KaTeX_Math-BoldItalic.ttf
          weight: 700
          style: italic
    - family: KaTeX_AMS
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_AMS-Regular.ttf
    - family: KaTeX_Caligraphic
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Caligraphic-Regular.ttf
        - asset: lib/katex_fonts/fonts/KaTeX_Caligraphic-Bold.ttf
          weight: 700
    - family: KaTeX_Fraktur
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Fraktur-Regular.ttf
        - asset: lib/katex_fonts/fonts/KaTeX_Fraktur-Bold.ttf
          weight: 700
    - family: KaTeX_SansSerif
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_SansSerif-Regular.ttf
        - asset: lib/katex_fonts/fonts/KaTeX_SansSerif-Bold.ttf
          weight: 700
        - asset: lib/katex_fonts/fonts/KaTeX_SansSerif-Italic.ttf
          style: italic
    - family: KaTeX_Script
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Script-Regular.ttf
    - family: KaTeX_Typewriter
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Typewriter-Regular.ttf
    - family: KaTeX_Size1
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Size1-Regular.ttf
    - family: KaTeX_Size2
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Size2-Regular.ttf
    - family: KaTeX_Size3
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Size3-Regular.ttf
    - family: KaTeX_Size4
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Size4-Regular.ttf
